### ISSUE TITLE
Nx 14

### ISSUE THREAD

**Issue by JoMas971** [orjandesmet/nx-sparse-checkout#20]
Is there any plan to update this lib to work with Nx 14 as well?

Thanks!

**Comment by orjandesmet** [comment]
I’m on holiday right now. Feel free to create a PR ;)

**Comment by JoMas971** [comment]
Well, between version 13 and 14 there where a lot of breaking changes... I've tried to take a look at it but i couldn't fix it.

In the `src/nrwl-utils.ts` file of this project we have:

```
import { getProjectRoots } from '@nrwl/workspace/src/command-line/shared';
import { readCachedProjectGraph, ProjectGraphNode } from '@nrwl/workspace/src/core/project-graph';
```

In version 14 they are not exporting the method `getProjectRoots` anymore (they've moved it onto a private util folder of `@nrwl/nx` project).
And there is no `ProjectGraphNode` type exported anymore as well.

I couldn't find any alternative on my side. And i'm pretty new to Nx so it will take me too much time to find a solution. 
So i'll use the native git sparse checkout for now (since i haven't found any other library compatible with Nx 14) and hope that this lib gets updated to work with Nx 14 :-)

Thank you!

**Comment by orjandesmet** [comment]
@JoMas971 I've pushed an updated version that works with Nx 14

**Comment by JoMas971** [comment]
WOW nice! Thanks a lot ! That is awesome!
